# Generated by Django 4.2.5 on 2023-10-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_record_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='city',
            field=models.CharField(blank=True, choices=[('Kerala', 'Kerala'), ('TamilNadu', 'TamilNadu'), ('Mexico', 'Mexico'), ('Chicago', 'Chicago')], max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('USA', 'USA')], max_length=50),
        ),
    ]
